"use client";

import { AlertOctagon, Clock, Info } from "lucide-react";
import { cn } from "@/lib/utils";
import { stripEmoji } from "@/lib/text";
import type { TranslateResult, UrgencyTier } from "@/lib/types";

/** Classification banner — color + icon driven by the AI's urgency tier. */
const URGENCY_STYLE: Record<
  UrgencyTier,
  { wrap: string; icon: typeof AlertOctagon; label: string }
> = {
  "Urgent Action Required": {
    wrap: "border-red-200 bg-red-50/50 text-red-800",
    icon: AlertOctagon,
    label: "Urgent action required",
  },
  "Time Sensitive": {
    wrap: "border-amber-100 bg-amber-50/40 text-amber-900",
    icon: Clock,
    label: "Time sensitive",
  },
  "Informational Only": {
    wrap: "border-primary/20 bg-primary/5 text-primary",
    icon: Info,
    label: "Informational only",
  },
};

export function UrgencyBanner({ tier, brief }: { tier: UrgencyTier; brief: string }) {
  const style = URGENCY_STYLE[tier] ?? URGENCY_STYLE["Informational Only"];
  const Icon = style.icon;
  return (
    <div className={cn("flex items-start gap-3 rounded-xl border p-3", style.wrap)}>
      <Icon className="mt-0.5 h-5 w-5 shrink-0" />
      <div>
        <p className="text-[10px] font-semibold uppercase tracking-wide opacity-80">AI classification</p>
        <p className="text-base font-bold leading-tight">{style.label}</p>
        {brief && <p className="mt-1 text-sm font-medium opacity-90">{brief}</p>}
      </div>
    </div>
  );
}

/** Compact urgency pill for the dashboard header. */
export function UrgencyPill({ tier, className }: { tier: UrgencyTier; className?: string }) {
  const style = URGENCY_STYLE[tier] ?? URGENCY_STYLE["Informational Only"];
  const Icon = style.icon;
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1.5 rounded-full border px-3 py-1 text-xs font-bold",
        style.wrap,
        className,
      )}
    >
      <Icon className="h-3.5 w-3.5" />
      {style.label}
    </span>
  );
}

/** Compact pill for the AI's self-reported extraction confidence. */
export function ConfidenceBadge({ score }: { score: TranslateResult["ai_confidence_score"] }) {
  return (
    <span
      className="inline-flex items-center gap-1 rounded-full border border-emerald-100 bg-emerald-50 px-2 py-0.5 text-[10px] font-medium text-emerald-700"
      title="How confident the AI is in the extracted details (including deadlines). Always verify against the original."
    >
      AI confidence: {score}
    </span>
  );
}

export function buildShareText(result: TranslateResult): string {
  const tasks = result.task_list.map((t, i) => `${i + 1}. ${stripEmoji(t.task)}`).join("\n");
  const intro = "My ClearAid action plan:";
  const footer = "Generated by ClearAid — paperwork, made plain.";
  return [intro, tasks || "(no tasks)", footer].filter(Boolean).join("\n\n");
}
