"use client";

import { ListChecks, Calendar } from "lucide-react";
import { Card } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Progress } from "@/components/ui/progress";
import { stripEmoji } from "@/lib/text";
import type { Translator } from "@/lib/i18n";
import type { TaskItem } from "@/lib/types";

function getMonthNumber(monthStr: string): number {
  const m = monthStr.toLowerCase();
  if (m.startsWith("jan")) return 0;
  if (m.startsWith("feb")) return 1;
  if (m.startsWith("mar")) return 2;
  if (m.startsWith("apr")) return 3;
  if (m.startsWith("may")) return 4;
  if (m.startsWith("jun")) return 5;
  if (m.startsWith("jul")) return 6;
  if (m.startsWith("aug")) return 7;
  if (m.startsWith("sep")) return 8;
  if (m.startsWith("oct")) return 9;
  if (m.startsWith("nov")) return 10;
  if (m.startsWith("dec")) return 11;
  return -1;
}

function extractDeadline(taskText: string): Date | null {
  const monthNames = [
    "january", "february", "march", "april", "may", "june",
    "july", "august", "september", "october", "november", "december",
    "jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"
  ];

  // 1. Matches: Month Day, Year (e.g. June 25, 2026 or June 25th, 2026 or Jun 25 2026)
  const pattern1 = new RegExp(
    `\\b(${monthNames.join("|")})\\s+(\\d{1,2})(?:st|nd|rd|th)?\\b,?\\s+(\\d{4})`,
    "i"
  );
  // 2. Matches: Day Month Year (e.g. 25 June 2026 or 25th June 2026)
  const pattern2 = new RegExp(
    `\\b(\\d{1,2})(?:st|nd|rd|th)?\\s+(${monthNames.join("|")})\\b,?\\s+(\\d{4})`,
    "i"
  );
  // 3. Matches: YYYY-MM-DD
  const pattern3 = /\b(\d{4})[-/](\d{1,2})[-/](\d{1,2})\b/;
  // 4. Matches: MM/DD/YYYY or MM-DD-YYYY
  const pattern4 = /\b(\d{1,2})[-/](\d{1,2})[-/](\d{4})\b/;

  let match;

  if ((match = taskText.match(pattern1))) {
    const monthStr = match[1];
    const day = parseInt(match[2], 10);
    const year = parseInt(match[3], 10);
    const month = getMonthNumber(monthStr);
    if (month !== -1) return new Date(year, month, day);
  }

  if ((match = taskText.match(pattern2))) {
    const day = parseInt(match[1], 10);
    const monthStr = match[2];
    const year = parseInt(match[3], 10);
    const month = getMonthNumber(monthStr);
    if (month !== -1) return new Date(year, month, day);
  }

  if ((match = taskText.match(pattern3))) {
    const year = parseInt(match[1], 10);
    const month = parseInt(match[2], 10) - 1;
    const day = parseInt(match[3], 10);
    return new Date(year, month, day);
  }

  if ((match = taskText.match(pattern4))) {
    const month = parseInt(match[1], 10) - 1;
    const day = parseInt(match[2], 10);
    const year = parseInt(match[3], 10);
    return new Date(year, month, day);
  }

  // Check for month and day without a year, e.g. "by June 25" or "on June 25th"
  const patternNoYear = new RegExp(
    `\\b(${monthNames.join("|")})\\s+(\\d{1,2})(?:st|nd|rd|th)?\\b`,
    "i"
  );
  if ((match = taskText.match(patternNoYear))) {
    const monthStr = match[1];
    const day = parseInt(match[2], 10);
    const month = getMonthNumber(monthStr);
    if (month !== -1) {
      const year = new Date().getFullYear();
      const d = new Date(year, month, day);
      const now = new Date();
      // If the date is already in the past by more than a month, assume it refers to next year
      if (d.getTime() < now.getTime() - 30 * 24 * 60 * 60 * 1000) {
        d.setFullYear(year + 1);
      }
      return d;
    }
  }

  return null;
}

function handleAddToCalendar(task: TaskItem, deadline: Date) {
  const title = stripEmoji(task.task);
  const description = `Deadline for task: ${title}. Generated by ClarityAI.`;

  const formatDateToICS = (date: Date): string => {
    const y = date.getFullYear();
    const m = String(date.getMonth() + 1).padStart(2, '0');
    const d = String(date.getDate()).padStart(2, '0');
    return `${y}${m}${d}`;
  };

  const icsContent = [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//ClarityAI//NONSGML Event//EN",
    "CALSCALE:GREGORIAN",
    "BEGIN:VEVENT",
    `UID:${Date.now()}-${task.id}@clarityai.app`,
    `DTSTAMP:${formatDateToICS(new Date())}T000000Z`,
    `DTSTART;VALUE=DATE:${formatDateToICS(deadline)}`,
    `DTEND;VALUE=DATE:${formatDateToICS(new Date(deadline.getTime() + 24 * 60 * 60 * 1000))}`,
    `SUMMARY:${title.replace(/[,;]/g, '\\$&')}`,
    `DESCRIPTION:${description.replace(/[,;]/g, '\\$&')}`,
    "END:VEVENT",
    "END:VCALENDAR"
  ].join("\r\n");

  const blob = new Blob([icsContent], { type: "text/calendar;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `task-${task.id}-deadline.ics`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Interactive checklist (CONTROLLED).
 *
 * Checked state is owned by a parent (the TranslatorApp orchestrator) and
 * persisted to localStorage there, so it is lifted high enough to survive
 * switching between dashboard tabs without wiping the user's progress.
 *
 * FAILSAFE: renders nothing when there are no tasks.
 */
export function TaskList({
  tasks,
  checked,
  onToggle,
  storageKey,
  t,
}: {
  tasks: TaskItem[];
  checked: Record<string, boolean>;
  onToggle: (id: string, value: boolean) => void;
  /** Used only to namespace the checkbox element ids. */
  storageKey: string;
  t: Translator;
}) {
  if (!tasks || tasks.length === 0) return null;

  const doneCount = tasks.filter((task) => checked[String(task.id)]).length;
  const pct = (doneCount / tasks.length) * 100;

  return (
    <Card>
      <div className="mb-2 flex items-center justify-between">
        <h2 className="flex items-center gap-2 text-xs font-semibold uppercase text-primary">
          <ListChecks className="h-4 w-4" /> {t("action_checklist")}
        </h2>
        <span className="text-xs font-semibold text-muted-foreground">
          {doneCount}/{tasks.length} {t("done")}
        </span>
      </div>

      <Progress value={pct} className="mb-3" />

      <div className="space-y-1.5">
        {tasks.map((task) => {
          const key = String(task.id);
          const deadline = extractDeadline(task.task);

          const labelContent = (
            <div className="flex flex-col w-full gap-0.5">
              <div className="flex items-center justify-between w-full gap-2">
                <span>{stripEmoji(task.task)}</span>
                {deadline && (
                  <button
                    type="button"
                    onClick={(e) => {
                      e.preventDefault();
                      e.stopPropagation();
                      handleAddToCalendar(task, deadline);
                    }}
                    className="flex h-8 w-8 shrink-0 items-center justify-center rounded-md border border-primary/20 bg-primary/5 text-primary shadow-clay-sm transition-all hover:bg-primary/10 active:translate-y-0.5 ml-auto"
                    title={t("add_to_calendar")}
                  >
                    <Calendar className="h-4 w-4" />
                  </button>
                )}
              </div>
              {task.description && (
                <span className="text-sm text-muted-foreground">{stripEmoji(task.description)}</span>
              )}
            </div>
          );

          return (
            <Checkbox
              key={key}
              id={`task-${storageKey}-${key}`}
              label={labelContent}
              labelClassName="text-sm w-full flex-grow"
              checked={!!checked[key]}
              onCheckedChange={(v) => onToggle(key, v)}
            />
          );
        })}
      </div>
    </Card>
  );
}
